### ISSUE TITLE
Bootstrapped Pair Testing Segmentation Fault

### ISSUE THREAD

**Issue by Guy-Mav** [apertium/apertium-init#78] opened 2020-01-28 04:19 UTC
I followed the tutorial for bootstrapping a pair with no existing monolingual dictionaries for both and when I tested it using the echo command(just like in the tutorial) i always get a segmentation fault

**Comment by TinoDidriksen** [comment] 2020-03-30 09:27
Probably duplicate of https://github.com/apertium/apertium-init/issues/31

**Closed** 2022-06-29 17:27 UTC
